### PR TITLE
Adjustable Start Index for Spans (Per Issue #355)

### PR DESCRIPTION
**Pull request by wtreid**
This commit addresses git issue 355 (https://github.com/crsmithdev/arrow/issues/355).  In addition to providing the ability to give a start index for a weekday, it also allows a user to give a start index for all spans but quarters.  For example, you could create a span of a month starting on the 7th of the month.

### CODE REVIEW

**Comment by andrewelkins** [comment]
Thanks for the extensive PR. I'll review shortly.

**Comment by rkunnamp** [comment]
This would be highly useful. Thanks.

**Comment by cadupont** [comment]
That would be super useful. @andrewelkins Is there anything we can do to speed up the process?
I'm quite interested by this update. Thanks

**Comment by Syeberman** [comment]
@wtreid @andrewelkins I have an idea to make this even more flexible: rename `start_index` to `shift`, and accept a dict of keywords as per the `shift()` function:

```python
arrow.utcnow().span('hour', shift={'minutes': 5})
```

This allows for, as an example, shifts of seconds when the span is an hour.  It's self-documenting, as the API and docs already define what the "shift" concept means.  It also greatly simplifies the PR, because the giant `if` statement becomes `floor = floor.shift(**shift)`.

**Comment by systemcatch** [comment]
@wtreid sorry for the delay on this. If we can fix the conflicts then use @Syeberman's suggestion then this can be merged.

**Comment by systemcatch** [comment]
This is a good idea but using @Syeberman's solution seems like the more elegant approach. If you'd like to re-implement this feel free to open another PR, but otherwise we hope to implement this in the future.

**Pull request closed without merging**
