### PR TITLE
Separate replace & shift function

### PR DESCRIPTION
**Pull request by sipp11**
According to PR Request from the issue #220, I also think it's a nice idea.

Basically ripping relativedelta part out of replace() to make a new function, shift() & refactoring all related tests.

### CODE REVIEW

**Comment by andrewelkins** [comment]
Excellent, I'll review this and get it merged.

**Comment by andrewelkins** [comment]
Looks solid. Let me do some testing locally before pushing out this breaking change.

**Comment by sipp11** [comment]
Oops, I miss something, the docs, `docs/index.rst`. However, docstrings are good enough, I hope.

**Comment by kdeldycke** [comment]
:100: : this is a huge usability gain !

**Comment by pypingou** [comment]
Would there be a way to make replace call shift so that it doesn't break backward compatibility?
Maybe with a deprecation warning in addition?

**Comment by sipp11** [comment]
@pypingou That shouldn't be a problem; however, I don't know if that's the best option. Let's hear what @andrewelkins says. I could do another PR if needed although I prefer the way this is.

**Comment by pypingou** [comment]
@sipp11 how would it not be a problem? All the calls to ``.replace()`` will suddenly stop working, that's pretty much breaking backward compatibility :)

**Comment by sipp11** [comment]
@pypingou Sorry I might reply you too short since it should have been __"That shouldn't be a problem to add deprecation warning."__ 

For the breaking change, I'm fine either way since I've fixed them all. Code is much easier to read :)

**Comment by pypingou** [comment]
It's easier to read and I think the change is great but breaking backward compatibility from a release to another is bad. I do think we should announce the change with a deprecation warning for a release (ideally two), then we can clean the code and get ride of ``.replace()``.

**Comment by andrewelkins** [comment]
That makes sense. Can we add the deprecation warning?

**Comment by sipp11** [comment]
Sorry that I couldn't do it sooner, but if you still need it, I restore replace functionality (to shift date) and add deprecation warning if using it. Hopefully I'll get another PR done too. I use this library too much and I hate to just pip from my fork.

**Comment by Syeberman** [comment]
I've resolved the merge conflicts in https://github.com/crsmithdev/arrow/issues/349

**Comment by andrewelkins** [comment]
Thanks @sipp11 for the original PR and @Syeberman I'll check out the new PR and close this one.

**Pull request closed without merging**
