### PR TITLE
Allow x token to be used in formatting

### PR DESCRIPTION
**Pull request by alstomli**
for "X" token now we can show timestamp in float number
for "x" token eliminated the zeros in the end

## Pull Request Checklist

Thank you for taking the time to improve Arrow! Before submitting your pull request, please check all *appropriate* boxes:

- [x] 🧪 Added **tests** for changed code.
- [x] 🛠️ All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [x] 📚 Updated **documentation** for changed code.
- [x] ⏩ Code is **up-to-date** with the `master` branch.

If you have *any* questions about your code changes or any of the points above, please submit your questions along with the pull request and we will try our best to help!

### CODE REVIEW

**Comment by alstomli** [comment]
the program now goes like this:

>>> arw = arrow.utcnow()
>>> arw.format('X')
'1575165260.480332'
>>> arw.format('x')
'1575165260480332'

**Comment by jadchaar** [comment]
Hi @alstomli, seems like you have merge conflicts. Mind resolving these conflicts and adding unit tests to test the new functionality?

**Comment by alstomli** [comment]
did some try

**Comment by alstomli** [comment]
fixed

**Comment by alstomli** [comment]
Hi @jadchaar  if it is ok, could you merge it as soon as possible, thanks a lot.

**Comment by systemcatch** [comment]
@alstomli can you rename your branch to something without any quotes, I'm having trouble checking out your branch on my machine.

**Comment by systemcatch** [comment]
It's not the PR name that is causing issues but the branch name, see https://stackoverflow.com/a/30590238 for various ways to change it.

**Comment by alstomli** [comment]
hi @systemcatch I have pulled a new request(#737 ) used my master branch in case of any conflict, it is the same as this one, sorry for the confusion.

**Comment by jadchaar** [comment]
Awesome @alstomli, thanks for updating the branch name. I am closing this PR in favor of the other one :).

**Pull request closed without merging**
