### PR TITLE
Python 3.7 support.

### PR DESCRIPTION
**Pull request by krisfremen**
Hello,

This pull request adds Python 3.7 support.

### CODE REVIEW

**Comment by sudoguy** [comment]
@krisfremen StopIteration is now replaced by RuntimeError (from python 3.7). But if you want to enable the same behaviour since python3.5 you can use 
```python
from __future__ import generator_stop
```

So, this exception won't be catch in python 3.7
https://github.com/crsmithdev/arrow/pull/544/files#diff-5d8eb9e97f8b648e4dae883cdce7b959R365

**Comment by krisfremen** [comment]
hey guys, sorry. I moved countries in the past few weeks.

**Comment by krisfremen** [comment]
@systemcatch ready to merge

**Comment by systemcatch** [comment]
Thanks @krisfremen!

**Pull request merged**
