### PR TITLE
Add tests to increase coverage and pass build.

### PR DESCRIPTION
**Pull request by Irishsmurf**
Noticed that the build was failing due to coverage within locales.py and util.py.
This commit fixes the build based on this.

https://travis-ci.org/Irishsmurf/arrow

### CODE REVIEW

**Comment by ownaginatious** [comment]
I believe someone actually fixed this back in September, but their pull request is yet to be accepted. I feel like this project has been abandoned by whoever the maintainers are...

**Comment by philiptzou** [comment]
Yeah I believe it so. I fixed it already.

**Comment by Irishsmurf** [comment]
Ah, that's a shame.

**Comment by seemethere** [comment]
Yup it's still sitting there at #289

**Comment by Irishsmurf** [comment]
Looks like #289 has been merged, I'll go ahead and close this.

**Pull request closed without merging**
