### PR TITLE
Added ArrowInterval class that conforms to the standards of the Joda interval (http://joda-time.sourceforge.net/apidocs/org/joda/time/Interval.html)

### PR DESCRIPTION
**Pull request by fatisar**

### CODE REVIEW

**Comment by kdeldycke** [comment]
What about using vocabulary from [Allen's interval algebra](https://en.wikipedia.org/wiki/Allen%27s_interval_algebra) instead ?

**Comment by Syeberman** [comment]
It looks like [Joda is deprecated](http://www.joda.org/joda-time/), and [its replacement](https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html) has no similar concept.

Arrow is inspired by Moment.js, which implements this as [methods on a moment](http://momentjs.com/docs/#/query/is-between/).  This might be a better direction for Arrow.

**Comment by andrewelkins** [comment]
Can confirm @Syeberman thoughts. We would prefer to stick close to moment.js where possible.

**Comment by Syeberman** [comment]
Thanks for the contribution @fatisar, and sorry for the delay, but this isn't the direction we want to take Arrow.

**Pull request closed without merging**
