### PR TITLE
Allow x token to be used in formatting

### PR DESCRIPTION
**Pull request by alstomli**
## Pull Request Checklist

Thank you for taking the time to improve Arrow! Before submitting your pull request, please check all *appropriate* boxes:

- [ ] 🧪 Added **tests** for changed code.
- [ ] 🛠️ All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [ ] 📚 Updated **documentation** for changed code.
- [ ] ⏩ Code is **up-to-date** with the `master` branch.

If you have *any* questions about your code changes or any of the points above, please submit your questions along with the pull request and we will try our best to help!

### CODE REVIEW

**Comment by systemcatch** [comment]
Hey @alstomli I've been checking out your branch and noticed that this is occurring.

```shell
(arrow) chris@ThinkPad:~/arrow$ python
Python 3.7.4 (default, Sep 19 2019, 11:01:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> arw=arrow.utcnow()
>>> arw
<Arrow [2019-12-22T19:44:08.492814+00:00]>
>>> arw.format("x")
'x'
```

**Comment by alstomli** [comment]
I have just tested the program on my machine but it seems there is nothing wrong:
>>> import arrow
>>> arrow.utcnow().format("x")
'1577074797676671'
>>> arw = arrow.utcnow()
>>> arw.format("x")
'1577074859157219'
>>> arw
<Arrow [2019-12-23T04:20:59.157219+00:00]>

**Comment by alstomli** [comment]
I have just tested the program on my machine it seems there is nothing wrong
`>>> import arrow
>>> arrow.utcnow().format("x")
'1577074797676671'
>>> arw = arrow.utcnow()
>>> arw.format("x")
'1577074859157219'
>>> arw
<Arrow [2019-12-23T04:20:59.157219+00:00]>`

**Comment by alstomli** [comment]
I will double check it later next week

**Comment by alstomli** [comment]
Hi @systemcatch if we need to add new "x" format I think we need to rewrite 
`r"(\[(?:(?=(?P<literal>[^]]))(?P=literal))*\]|YYY?Y?|MM?M?M?|Do|DD?D?D?|d?dd?d?|HH?|hh?|mm?|ss?|SS?S?S?S?S?|ZZ?Z?|a|A|X)"` into `r"(\[(?:(?=(?P<literal>[^]]))(?P=literal))*\]|YYY?Y?|MM?M?M?|Do|DD?D?D?|d?dd?d?|HH?|hh?|mm?|ss?|SS?S?S?S?S?|ZZ?Z?|a|A|X|x)"` so the program can detect the new token, however, when I submitted this change it says it is an conflit, is there any way to solve this?

**Comment by jadchaar** [comment]
Hey, we are going to close this for now since we are pushing these changes to when we drop Python 2.7 support because this will allow us to introduce some breaking changes to the existing API.

**Pull request closed without merging**
