### PR TITLE
Add week granulation and week locale handling

### PR DESCRIPTION
**Pull request by jadchaar**
Fixes conflicts of this stale PR: https://github.com/crsmithdev/arrow/pull/529.

Closes: https://github.com/crsmithdev/arrow/issues/524

### CODE REVIEW

**Comment by systemcatch** [comment]
hey @jadchaar can you post an example of this in action

**Comment by systemcatch** [comment]
```python
>>> arrow.get('2018-01-12T00:00:00.000-07:00').humanize(locale='en', granularity='week')
'83 weeks ago'
```

Looks to be working ok.

**Comment by jadchaar** [comment]
Where should I post the example? In the documentation or the docstring?

Also, I made a branch off of this to make a few improvements to handling of key errors on untranslated time frames, so I will PR that with the example as well.

**Comment by systemcatch** [comment]
> Where should I post the example? In the documentation or the docstring?
> 
> Also, I made a branch off of this to make a few improvements to handling of key errors on untranslated time frames, so I will PR that with the example as well.

Hey no I meant just in this PR showing the fix was working.

**Pull request merged**
