### PR TITLE
Implement weekday shifting for #64

### PR DESCRIPTION
**Pull request by BonkaBonka**
I’m not terribly happy with the implementation - I don’t grok why
dateutil handles some values (negatives and zeroes) the way it does,
but I figure this is good to generate discussion anyway.

### CODE REVIEW

**Comment by AlJohri** [comment]
@andrewelkins can you release this in a new version of arrow? the docs are deployed and this is causing confusion: see #450 and #489

**Comment by Syeberman** [comment]
@AlJohri 0.12 was released over the weekend.  Does it work for you now?

**Comment by AlJohri** [comment]
@Syeberman I tried yesterday with the latest in master and it didn't work - I will try again though. really looking forward to this feature :)

**Comment by AlJohri** [comment]
@Syeberman seems like I was using `replace` instead of `shift`. Any reason this doesn't work with `replace`?

```
(arrowtest-UpwQbFbR) Als-MacBook-Pro # python                                                                      [~/Development/arrowtest]
Python 3.6.3 (default, Oct 28 2017, 20:10:09)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> arrow.now()
<Arrow [2017-11-27T12:37:37.079129-05:00]>
>>> arrow.now().replace(weekdays=-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johria/.local/share/virtualenvs/arrowtest-UpwQbFbR/lib/python3.6/site-packages/arrow/arrow.py", line 488, in replace
    raise AttributeError('unknown attribute: "{0}"'.format(key))
AttributeError: unknown attribute: "weekdays"
>>> arrow.now().replace(weekday=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johria/.local/share/virtualenvs/arrowtest-UpwQbFbR/lib/python3.6/site-packages/arrow/arrow.py", line 488, in replace
    raise AttributeError('unknown attribute: "{0}"'.format(key))
AttributeError: unknown attribute: "weekday"
>>> arrow.now().shift(weekday=0)
<Arrow [2017-11-27T12:38:24.345087-05:00]>
>>> arrow.now().shift(weekday=1)
<Arrow [2017-11-28T12:38:31.673294-05:00]>
>>>
```

**Comment by Syeberman** [comment]
@AlJohri We've moved all the increment/decrement functionality out of `replace` and into `shift`, because it was too easy to mistype `days` as `day` (or vice versa) and get completely the wrong behaviour.  You can still chain the calls together if you need the behaviour of both:

`arw.replace(month=1).shift(days=-3)`

**Pull request merged**
