### PR TITLE
arrow.get(): Implement d, ddd and ddd

### LINKED ISSUE #281: Day of week parsing does not work
It seems like the following should work:
```
some_date = 'Wed 6 Jun 2007 23:13:53'
fmt = 'ddd D MMM YYYY HH:mm:ss'
arrow.get(some_date, fmt)
```
But it throws a `ParserError`.  Note that the parsing works without the day of the week, and `.format` handles things fine:

```
arrow.get(some_date[4:], fmt[4:]).format(fmt) == some_date  # True
```

### PR DESCRIPTION
**Pull request by dmerejkowsky**
The branch is named twitter because I had trouble parsing dates returned by twitter API, which
look like:  Fri Apr 08 19:19:24 +0000 2016

Fixes #281 and #273

### CODE REVIEW

**Comment by dmerejkowsky** [comment]
I just realized. You can workaround the bug by using:

```python
date = arrow.Arrow.strptime("Fri Apr 08 19:19:24 +0000 2016",  "%a %b %d %H:%M:%S %z %Y")
```

**Comment by jcollie** [comment]
Despite there being a workaround, it would be better to have days of the week parsed by the standard get method - there are lots of date formats that include the day of the week.  RFC2822 email being a major one.

**Comment by dmerejkowsky** [comment]
@jcollie I agree :)

**Comment by dmerejkowsky** [comment]
Thanks for merging :)

**Pull request merged**
