### PR TITLE
Fix SyntaxWarning due to escape sequences and enable Python 3.8 build

### LINKED ISSUE #584: SyntaxWarning in Python 3.8
Running tests on CPython master gives me below SyntaxWarnings. This could be fixed by prefixing 'r' in front of the strings . Upstream PR https://github.com/python/cpython/pull/9652 . I will raise a PR for this shortly.

```
/home/karthi/arrow/arrow/parser.py:24: SyntaxWarning: invalid escape sequence \[
  _ESCAPE_RE = re.compile('\[[^\[\]]*\]')
/home/karthi/arrow/arrow/parser.py:26: SyntaxWarning: invalid escape sequence \d
  _ONE_OR_MORE_DIGIT_RE = re.compile('\d+')
/home/karthi/arrow/arrow/parser.py:27: SyntaxWarning: invalid escape sequence \d
  _ONE_OR_TWO_DIGIT_RE = re.compile('\d{1,2}')
/home/karthi/arrow/arrow/parser.py:28: SyntaxWarning: invalid escape sequence \d
  _FOUR_DIGIT_RE = re.compile('\d{4}')
/home/karthi/arrow/arrow/parser.py:29: SyntaxWarning: invalid escape sequence \d
  _TWO_DIGIT_RE = re.compile('\d{2}')
/home/karthi/arrow/arrow/parser.py:30: SyntaxWarning: invalid escape sequence \-
  _TZ_RE = re.compile('[+\-]?\d{2}:?(\d{2})?')
/home/karthi/arrow/arrow/parser.py:31: SyntaxWarning: invalid escape sequence \w
  _TZ_NAME_RE = re.compile('\w[\w+\-/]+')
/home/karthi/arrow/arrow/parser.py:49: SyntaxWarning: invalid escape sequence \d
  'X': re.compile('\d+'),
/home/karthi/arrow/arrow/parser.py:157: SyntaxWarning: invalid escape sequence \#
  a = fmt_pattern.split("\#")
/home/karthi/arrow/arrow/parser.py:313: SyntaxWarning: invalid escape sequence \-
  _TZINFO_RE = re.compile('([+\-])?(\d\d):?(\d\d)?')
/home/karthi/arrow/arrow/parser.py:49: SyntaxWarning: invalid escape sequence \d
  'X': re.compile('\d+'),
/home/karthi/arrow/arrow/parser.py:157: SyntaxWarning: invalid escape sequence \#
  a = fmt_pattern.split("\#")
/home/karthi/arrow/arrow/parser.py:313: SyntaxWarning: invalid escape sequence \-
  _TZINFO_RE = re.compile('([+\-])?(\d\d):?(\d\d)?')

```

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #584

### CODE REVIEW

**Comment by systemcatch** [comment]
Hello @tirkarthi, thank you for the PR.

We don't build against Python 3.8 on travis yet, however seeing as it's scheduled for mainstream release in October 2019 it's probably a good idea to start doing so. Once version 0.13.2 is released I will add 3.8 to travis, feel free to do this yourself if you have time.

**Comment by tirkarthi** [comment]
This is actually a `DeprecationWarning` in 3.7 and was later promoted to `SyntaxWarning` in 3.8 . In `.travis.yml` you can specify `- nightly` like `- 3.7` which will automatically start building on latest dev release (3.8 alpha 4 now). Do you want me to add it as part of this PR to travis config ?

Sample DeprecationWarning in Python 3.7. DeprecationWarnings are disabled by default which could be a reason they are not shown in CI.

```
python3.7 -Wall
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> '\d'
<stdin>:1: DeprecationWarning: invalid escape sequence \d
'\\d'
```

**Comment by systemcatch** [comment]
That would great if you're willing to do that. Let's add `nightly` to travis but allow failure on that build for now until things get a little more stable.

There's also the question of whether to enable some of these warnings in the build otherwise they may get missed. We probably don't need warnings from arrow but stdlib stuff would be useful.

**Comment by tirkarthi** [comment]
I have enabled nightly but I don't have any idea on enabling stdlib only warnings. I will do it as a separate PR if I come across a way to do it.

**Comment by jadchaar** [comment]
Hah funny thing! I came across this exact issue when making `arrow` flake8 compliant, so this is a great change. Any difference between `3.8-dev` and `nightly` on Travis?

**Comment by tirkarthi** [comment]
I think nightly points to master (currently 3.8 dev) and 3.8-dev points to latest 3.8. Hence after 3.8 release 3.8-dev will run on 3.8.0, 3.8.1 and so on while nightly builds on master (upcoming 3.9 dev). I cannot confirm but that's what I could infer from https://docs.travis-ci.com/user/languages/python/#nightly-build-support

**Comment by jadchaar** [comment]
Would it be better to mark the Travis target to `3.8-dev` then? Because then we won't have to worry when the master points to `>=3.9`. Of course, that will not be for a while, but I thought I'd mention it.

I wonder if `3.8-dev` lags the nightly. I wish the Travis docs were a bit more details in that respect.

**Comment by jadchaar** [comment]
So I figured out how we can display `stdlib` errors on a Travis run: we can run `nose` as a module and set a flag (`-Wd`)for Python to display all warnings.

I was thinking we could make a separate target for testing the dev releases:
```make
test-dev:
	rm -f .coverage
	. local/bin/activate && local/bin/python3 -Wd -m nose
```

**Comment by tirkarthi** [comment]
@jadchaar Thanks, I have changed to 3.8-dev. Sorry, I might not have time to expand the scope of the PR to include warnings so if someone wants to do that please go ahead.

**Comment by jadchaar** [comment]
Looks good to me. I actually looked at the Travis builds between `nightly` and `3.8-dev` and they both build `Python 3.8a3`, so the change to dev is solid. Thanks for the contribution @tirkarthi.

**Comment by tirkarthi** [comment]
Thank you all for the review :)

**Pull request merged**
