### PR TITLE
Improved humanize behavior for near-zero durations

### PR DESCRIPTION
**Pull request by jadchaar**
Since @TroyStacer and I were already working on fixing issue #541 in Humanize, we thought we would tackle bug #416 as well since the PR and issue for it has been stale since mid 2017.

Fixes: https://github.com/crsmithdev/arrow/issues/416

The original PR for this issue (https://github.com/crsmithdev/arrow/pull/417) did not seem to fully address the issue and had failing tests, so we decided to open a new PR with fresh changes and updates.

### CODE REVIEW

**Comment by jadchaar** [comment]
Thanks for the approval @systemcatch. One question though: would you like us to remove the docstrings comments from the inherited methods in the locales? Since describe is an internal method, it may not make much sense to keep the docstring comments. Would it be better to replace them with an inline comment explaining the rationale for the design decision?

**Comment by systemcatch** [comment]
hey @jadchaar, sure if you feel like it but no need to go to any great effort.

**Comment by jadchaar** [comment]
If I remove the docstrings from the two locales that override the describe method (English and German) to clean things up and reduce duplication, will Sphinx automatically copy over the parent classes docstring? I was reading online on a StackOverflow post that this seems to be the case, but I wanted to confirm :).

**Comment by systemcatch** [comment]
@jadchaar I think it will copy over (https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_inherit_docstrings) but it's fine to leave things as they are.

**Comment by jadchaar** [comment]
@systemcatch I agree. The duplication is a bit bothersome, but I think it is better for the sake of usability in something like VSCode, even if the inheritance of docs works fine with Sphinx. This seems good to go then :D.

**Pull request merged**
