### PR TITLE
Adding start_of and end_of methods

### PR DESCRIPTION
**Pull request by juanda95**
I've made this methods to move between the start and the end of the units in a date.

I got the idea from the Javascript library momentJS, and thought that it would be good to have a similar functionality in Arrow.

### CODE REVIEW

**Comment by woakas** [comment]
Any update of this PR? this feature is really helpful for me.

**Comment by jaapz** [comment]
@woakas isn't this the same functionality as `floor` and `ceil`?

**Comment by juanda95** [comment]
@jaapz Oh my... You're right about those methods. I didn't knew they existed, I'm very sorry.

I'm going to close this PR as the functionality is supported by `floor` and `ceil`.

**Comment by jaapz** [comment]
Haha, no problem, thanks for contributing anyway 🎉

**Comment by woakas** [comment]
@jaapz thanks.

**Pull request closed without merging**
