### PR TITLE
Drop support for EOL Python 2.6 and 3.3, add support for 3.6

### LINKED ISSUE #426: Drop support for Python 2.6?
https://travis-ci.org/crsmithdev/arrow/jobs/212040401#L116 says: _DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6_

Python 2.6 End of Life was in 2013... https://docs.python.org/devguide/index.html#branchstatus

Should arrow drop support for Python 2.6?

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #426.

Here's the pip installs for arrow from PyPI for the last month:
```
$ pypinfo --percent --pip arrow pyversion
python_version percent download_count
-------------- ------- --------------
2.7              59.8%        880,090
3.6              35.4%        520,727
3.4               2.5%         36,115
3.5               2.2%         32,627
3.3               0.0%            616
2.6               0.0%            534
3.7               0.0%            386
3.2               0.0%              7
None              0.0%              1

```

### CODE REVIEW

**Comment by hugovk** [comment]
@crsmithdev Hello, any thoughts on this PR (and my other ones)? Thank you!

**Comment by rhan-mentad** [comment]
My personal thought is to wait until a formal 1.0 before dropping 2.6/3.3. There's no technical reason why they need to be dropped now and it will just create problems for them to install.

**Comment by hugovk** [comment]
@rhan-mentad Good point, but good news! That impediment has been removed: 

I see 0.10 (2016-11-29) is the last one listed at https://github.com/crsmithdev/arrow/releases, but https://pypi.python.org/pypi/arrow has a recent 0.12 (2017-11-25). 

I've also added `python_requires` to setup.py, so pip can install the correct release for a user's Python version (see https://stackoverflow.com/a/44660547/724176).

**Comment by hugovk** [comment]
Rebased on master to resolve conflicts.

**Comment by danqing** [comment]
Any updates @Syeberman @crsmithdev ? Would love to see this merged.

**Comment by hugovk** [comment]
Added a commit to upgrade Python syntax using https://github.com/asottile/pyupgrade.

And stats for June 2018:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.6            |  85.29% |      1,126,421 |
| 2.7            |  10.96% |        144,792 |
| 3.4            |   1.87% |         24,728 |
| 3.5            |   1.82% |         23,975 |
| 3.7            |   0.04% |            513 |
| 2.6            |   0.01% |            159 |
| 3.3            |   0.01% |            132 |
| 3.8            |   0.00% |              1 |
| Total          |         |      1,320,721 |

**Comment by systemcatch** [comment]
I'm looking this one over now, just reran the builds and everything passed ok.

**Comment by systemcatch** [comment]
At the moment I'm waiting on input from @crsmithdev regarding whether we do this since it involves dropping support for old versions. Technically all seems ok. The other question is whether we release a new version now or wait until this is merged in.

**Pull request merged**
