### PR TITLE
Always open README with utf-8 encoding

### PR DESCRIPTION
**Pull request by andrewmwilson**
This is another regression in 0.14.0

Fixes: https://github.com/crsmithdev/arrow/issues/600

### CODE REVIEW

**Comment by jadchaar** [comment]
@andrewmwilson  Looks good. Any difference between `with codecs.open` and `with open("README.rst", "r", encoding="utf-8") as f:`?

**Comment by andrewmwilson** [comment]
@jadchaar I don't think the `encoding` parameter exists in Python 2.

There is also `io.open` in Python 2.6+.

**Comment by jadchaar** [comment]
You are very right! Also, mind adding `encoding='utf-8'` to the reading of `init.py`?

Then we can get this merged in.

**Comment by andrewmwilson** [comment]
Done!

**Comment by jadchaar** [comment]
Thanks for the contribution @andrewmwilson. Apologies for these regressions; hopefully this will be the last one :).

**Pull request merged**
